version: "3.1"

networks:
  app-tier:
    driver: bridge
services:
  mysql:
    networks:
      - app-tier
    image: mysql
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=q1w2e3r4r
      - MYSQL_USER=blueuser
      - MYSQL_PASSWORD=q1w2e3r4
      - MYSQL_DATABASE=bestwaydb
  app:
    networks:
      - app-tier
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    restart: always
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql